/**
 * parsers.test.ts
 * parseJsonl 对 Claude Code session JSONL 的回归测试。
 * 背景：2026-07-13 CLI Collector 误合并 bug —— 真实格式的用户消息是
 * type:"user"（非 "human"），旧实现丢弃全部用户消息导致标题/去重锚点退化。
 * 见 src/docs/debugging/2026-07-13-claude-jsonl-user-type-mismatch.md。
 */
import { describe, it, expect } from "vitest";
import { parseJsonl, parseMarkdown } from "./parsers.js";

/** 按真实 Claude Code session jsonl 的行结构构造 fixture。 */
const line = (obj: unknown) => JSON.stringify(obj);

const realSessionJsonl = [
  // 会话开头的非消息记录（应被忽略）
  line({ type: "file-history-snapshot", messageId: "fh_1" }),
  line({ type: "mode", mode: "default" }),
  // isMeta 元信息（本地命令 caveat，应被跳过）
  line({
    type: "user",
    isMeta: true,
    message: { role: "user", content: "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>" },
    timestamp: "2026-07-10T08:55:50.000Z",
  }),
  // 斜杠命令包裹（应被跳过）
  line({
    type: "user",
    message: { role: "user", content: "<command-name>/model</command-name>\n<command-message>model</command-message>" },
    timestamp: "2026-07-10T08:55:51.000Z",
  }),
  line({
    type: "user",
    message: { role: "user", content: "<local-command-stdout>Set model to sonnet</local-command-stdout>" },
    timestamp: "2026-07-10T08:55:52.000Z",
  }),
  // 真实用户消息（type 是 "user" 而非 "human"）
  line({
    type: "user",
    message: { role: "user", content: "帮我排查这个采集器 bug" },
    timestamp: "2026-07-10T08:55:53.259Z",
  }),
  // 助手消息：content 为块数组，含 thinking / tool_use 干扰项
  line({
    type: "assistant",
    message: {
      role: "assistant",
      content: [
        { type: "thinking", thinking: "内部推理不应出现在正文" },
        { type: "text", text: "好的，我先看采集器的解析逻辑。" },
        { type: "tool_use", id: "toolu_01", name: "Read", input: {} },
      ],
    },
    timestamp: "2026-07-10T08:55:55.000Z",
  }),
  // tool_result 回传（type:"user" 但无 text 块，应被跳过）
  line({
    type: "user",
    message: { role: "user", content: [{ type: "tool_result", tool_use_id: "toolu_01", content: "file contents" }] },
    timestamp: "2026-07-10T08:55:56.000Z",
  }),
  // 子代理 sidechain 消息（应被跳过）
  line({
    type: "user",
    isSidechain: true,
    message: { role: "user", content: "子代理的独立提示词" },
    timestamp: "2026-07-10T08:55:57.000Z",
  }),
  line({
    type: "assistant",
    isSidechain: true,
    message: { role: "assistant", content: [{ type: "text", text: "子代理的回复" }] },
    timestamp: "2026-07-10T08:55:58.000Z",
  }),
].join("\n");

describe("parseJsonl · Claude Code session 格式", () => {
  it("解析 type:\"user\" 的用户消息并以其作为标题", () => {
    const conv = parseJsonl(realSessionJsonl);
    expect(conv).not.toBeNull();
    expect(conv!.platform).toBe("Claude");
    expect(conv!.title).toBe("帮我排查这个采集器 bug");
    expect(conv!.messages.map((m) => m.role)).toEqual(["user", "ai"]);
    expect(conv!.messages[0].content).toBe("帮我排查这个采集器 bug");
    expect(conv!.messages[1].content).toBe("好的，我先看采集器的解析逻辑。");
  });

  it("跳过 isMeta / 斜杠命令 / tool_result / sidechain 记录", () => {
    const conv = parseJsonl(realSessionJsonl)!;
    const all = conv.messages.map((m) => m.content).join("\n");
    expect(all).not.toContain("local-command");
    expect(all).not.toContain("command-name");
    expect(all).not.toContain("file contents");
    expect(all).not.toContain("子代理");
    expect(all).not.toContain("内部推理");
  });

  it("只含命令/元信息记录的 session 返回 null（无真实对话）", () => {
    const onlyCommands = [
      line({ type: "user", isMeta: true, message: { role: "user", content: "<local-command-caveat>Caveat</local-command-caveat>" } }),
      line({ type: "user", message: { role: "user", content: "<command-name>/exit</command-name>" } }),
      line({ type: "user", message: { role: "user", content: "<local-command-stdout>Bye!</local-command-stdout>" } }),
    ].join("\n");
    expect(parseJsonl(onlyCommands)).toBeNull();
  });

  it("用户消息以换行开头时标题取 trim 后的首行", () => {
    const jsonl = [
      line({
        type: "user",
        message: { role: "user", content: "\n你是世界级的视觉设计师\n请输出单文件 HTML" },
        timestamp: "2026-06-24T10:54:07.031Z",
      }),
      line({ type: "assistant", message: { role: "assistant", content: [{ type: "text", text: "好的" }] } }),
    ].join("\n");
    const conv = parseJsonl(jsonl);
    expect(conv!.title).toBe("你是世界级的视觉设计师");
  });

  it("兼容旧导出格式 type:\"human\"", () => {
    const legacy = [
      line({ type: "human", message: { content: "旧格式的用户提问" }, timestamp: "2025-01-01T00:00:00.000Z" }),
      line({ type: "assistant", message: { content: "旧格式的回答" }, timestamp: "2025-01-01T00:00:05.000Z" }),
    ].join("\n");
    const conv = parseJsonl(legacy);
    expect(conv).not.toBeNull();
    expect(conv!.title).toBe("旧格式的用户提问");
    expect(conv!.messages.map((m) => m.role)).toEqual(["user", "ai"]);
  });

  it("用户消息混有 local-command-caveat 与斜杠命令时只保留真实提问", () => {
    // waylog / 未标 isMeta 的 caveat 与真实提问拼在同一条 user 消息里
    const jsonl = [
      line({
        type: "user",
        message: {
          role: "user",
          content:
            "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>\n\n> /model\n\n> ⎿ Set model to Sonnet 4.6 (default)\n\n我需要新增一个提案：需登录鉴权的页面采集",
        },
        timestamp: "2026-07-02T06:38:44.000Z",
      }),
      line({
        type: "assistant",
        message: { role: "assistant", content: [{ type: "text", text: "好的，我来写提案。" }] },
      }),
    ].join("\n");
    const conv = parseJsonl(jsonl)!;
    expect(conv.title).toBe("我需要新增一个提案：需登录鉴权的页面采集");
    expect(conv.messages[0].content).toBe("我需要新增一个提案：需登录鉴权的页面采集");
    expect(conv.messages[0].content).not.toContain("local-command-caveat");
    expect(conv.messages[0].content).not.toContain("/model");
  });
});

describe("parseMarkdown · waylog / Claude 用户段噪声", () => {
  it("剥离 User 段中的 local-command-caveat 与斜杠命令回显", () => {
    const md = `---
provider: claude
session_id: waylog-demo
---

## User
<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>

> /clear

> ⎿ (no content)

帮我排查采集器 bug

## Assistant
先看解析逻辑。
`;
    const conv = parseMarkdown(md)!;
    expect(conv.messages.map((m) => [m.role, m.content])).toEqual([
      ["user", "帮我排查采集器 bug"],
      ["ai", "先看解析逻辑。"],
    ]);
    expect(conv.title).toBe("帮我排查采集器 bug");
  });

  it("纯命令会话（无真实用户提问）返回 null", () => {
    const md = `---
provider: claude
---

## User
<local-command-caveat>Caveat</local-command-caveat>

> /exit

> ⎿ Catch you later!
`;
    expect(parseMarkdown(md)).toBeNull();
  });
});
